### PR TITLE
Fixes #68 by increasing the timeout for entering an ASG host into sta…

### LINKED ISSUE #68: elb-v2 scripts stopped working
I've had the elb-v2 working brilliantly in production for months, and all of a sudden this week deploys no longer succeed.

They fail on `Application Stop` with the following logs:

```
...
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance is currently in state: EnteringStandby
[stderr]Instance failed to reach state, Standby within 60 seconds
```

### PR DESCRIPTION
**Pull request by mmerkes**
…ndby for elb-v2 scripts

As described in issue #68, AutoScaling released a change that started honoring connection draining timeouts with ALBs, so this increases the timeout we wait to put an ASG host into standby so that it works in the default case. See issue for more details.

I manually tested the changes [here](https://github.com/mmerkes/sampleApp), and it seems to work.

### CODE REVIEW

File: load-balancing/elb-v2/common_functions.sh [hunk 1]
```diff
@@ -374,15 +380,23 @@ wait_for_state() {
         return 1
     fi
 
-    msg "Checking $WAITER_ATTEMPTS times, every $waiter_interval seconds, for instance $instance_id to be in state $state_name"
+    # Check if a custom waiter_attempts was passed into the function
+    # and override the attemps if true
+    if [ -n ${var+5} ]; then
```
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: Can you translate this line for me? I understand the comment above makes sense... but what does "-n ${var+5}" mean?

Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: Oops, this is wrong. Basically, I'm checking for a non-empty string.

File: load-balancing/elb-v2/common_functions.sh [hunk 2]
```diff
@@ -374,15 +380,23 @@ wait_for_state() {
...
+        local waiter_attempts=$5
```
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: Is this supposed to be 5 or $5? My bash-fu is lacking so I don't know.

File: load-balancing/elb-v2/common_functions.sh (hunk 1 above)
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: I looked it up: https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash . Is 5 a variable here or a constant?

File: load-balancing/elb-v2/common_functions.sh (hunk 2 above)
Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: This should be "$5"

File: load-balancing/elb-v2/common_functions.sh (hunk 1 above)
Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: I believe it should be -n "$5"

File: load-balancing/elb-v2/common_functions.sh (hunk 2 above)
Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: It is supposed to be $5. I want to set it as the fifth argument if it doesn't already exist.

File: load-balancing/elb-v2/common_functions.sh (hunk 1 above)
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: You should read that stackoverflow post, I actually think var+5 is correct then...

**Comment by mmerkes** [comment]
I updated the code. I'll let you know after I verify that I can deploy successfully.

File: load-balancing/elb-v2/common_functions.sh (hunk 2 above)
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: Hmm... to me that's very confusing as I'm not used to bash's way of doing that. Can you instead grab all the arguments in the beginning of the script / method? Then here refer to the variable instead?

Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: Sure, that makes sense.

**Comment by mmerkes** [comment]
@asaf-erlich I did a couple of successful deployment, and it works correctly now. I also validated that the timeout remains the same in other scenarios.

File: load-balancing/elb-v2/common_functions.sh [hunk 3]
```diff
@@ -374,15 +381,21 @@ wait_for_state() {
         return 1
     fi
 
-    msg "Checking $WAITER_ATTEMPTS times, every $waiter_interval seconds, for instance $instance_id to be in state $state_name"
+    # Check if a custom waiter_attempts was passed into the function
+    # and override the attemps if true
+    if [ -z "$waiter_attempts" ]; then
```
Comment (asaf-erlich) [inline load-balancing/elb-v2/common_functions.sh]: I think you should go back to ${var+waiter_attempts} because it distinguishes between unset and empty string: https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash

Comment (mmerkes) [inline load-balancing/elb-v2/common_functions.sh]: I believe that it's actually supposed to be `${waiter_attempts+x}`. However, in this case, being an empty string or null are essentially the same, so I think `"$waiter_attempts"` is the right way.
